# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-25 06:56
from __future__ import unicode_literals

import acutserver.core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle_Log',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('p1_vote', models.PositiveIntegerField(default=0)),
                ('p2_vote', models.PositiveIntegerField(default=0)),
                ('skip', models.PositiveIntegerField(default=0)),
                ('finish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Like_table',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('battle_log_id', models.ForeignKey(db_column='battle_log_id', on_delete=django.db.models.deletion.CASCADE, to='acutserver.Battle_Log')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to=acutserver.core.models.user_directory_path)),
                ('text', models.TextField(null=True)),
                ('victory', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('lounge', models.BooleanField(default=True)),
                ('new', models.BooleanField(default=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='upload_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=30)),
                ('image', models.ImageField(upload_to=acutserver.core.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30, null=True)),
                ('user_id', models.CharField(max_length=30, unique=True)),
                ('pw', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('profile_thumb', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, null=True)),
                ('user_type', models.CharField(default='normal', max_length=20)),
                ('vote', models.PositiveIntegerField(default=0)),
                ('win_vote', models.PositiveIntegerField(default=0)),
                ('my_vote', models.PositiveIntegerField(default=0)),
                ('battle', models.PositiveIntegerField(default=0)),
                ('win', models.PositiveIntegerField(default=0)),
                ('state', models.BooleanField(default=True)),
                ('last_session', models.DateTimeField()),
                ('facebook', models.CharField(max_length=100)),
                ('kakao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddField(
            model_name='upload_file',
            name='user_index',
            field=models.ForeignKey(db_column='user_index', default='', on_delete=django.db.models.deletion.CASCADE, to='acutserver.User'),
        ),
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='acutserver.User'),
        ),
        migrations.AddField(
            model_name='like_table',
            name='photo_id',
            field=models.ForeignKey(db_column='photo_index', on_delete=django.db.models.deletion.CASCADE, to='acutserver.Photo'),
        ),
        migrations.AddField(
            model_name='like_table',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='acutserver.User'),
        ),
        migrations.AddField(
            model_name='battle_log',
            name='p1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1_id', to='acutserver.Photo'),
        ),
        migrations.AddField(
            model_name='battle_log',
            name='p2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2_id', to='acutserver.Photo'),
        ),
        migrations.AlterIndexTogether(
            name='like_table',
            index_together=set([('user_id', 'battle_log_id', 'photo_id')]),
        ),
        migrations.AlterIndexTogether(
            name='battle_log',
            index_together=set([('p1_id', 'p2_id')]),
        ),
    ]
