# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 13:12
from __future__ import unicode_literals

import acutserver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upload_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='no user name', max_length=100)),
                ('image', models.ImageField(upload_to=acutserver.models.user_directory_path)),
            ],
        ),
    ]
