# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acutserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_index', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=30)),
                ('user_pw', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('user_img', models.CharField(max_length=100, null=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_type', models.CharField(max_length=20)),
                ('ticket', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
