# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 13:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acutserver', '0003_auto_20170413_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 25, 22, 7, 32, 875581)),
        ),
        migrations.AlterField(
            model_name='challenger',
            name='ch1_post_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ch1_post_index', to='acutserver.Post'),
        ),
        migrations.AlterField(
            model_name='challenger',
            name='ch2_post_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ch2_post_index', to='acutserver.Post'),
        ),
    ]
