# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 15:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acutserver', '0003_auto_20170505_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 5, 0, 57, 48, 511158)),
        ),
    ]
