# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acutserver', '0003_auto_20170715_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='like_table',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
