# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acutserver', '0004_like_table_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like_table',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='user',
            name='alarm_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterIndexTogether(
            name='battle_log',
            index_together=set([]),
        ),
    ]
