# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 13:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acutserver', '0004_auto_20170425_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follower_user_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_user_index', to='acutserver.User'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following_user_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_user_index', to='acutserver.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 25, 22, 10, 45, 936858)),
        ),
    ]
