# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 16:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acutserver', '0004_auto_20170505_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 5, 1, 9, 54, 506478)),
        ),
    ]
