# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acutserver', '0005_auto_20170719_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
