# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 16:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acutserver', '0005_auto_20170505_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 5, 1, 19, 20, 845076)),
        ),
    ]
