# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acutserver', '0006_photo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pw',
            field=models.CharField(max_length=100),
        ),
    ]
