# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-06 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acutserver', '0008_auto_20170730_1711'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='like_table',
            index_together=set([]),
        ),
    ]
