# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-06 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acutserver', '0009_auto_20170806_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
