# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-09 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acutserver', '0011_auto_20170909_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle_log',
            name='finished_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battle_log',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
