# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-16 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acutserver', '0012_auto_20170909_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle_log',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
