# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 16:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acutserver', '0013_auto_20170508_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 8, 1, 17, 13, 31233)),
        ),
    ]
