# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-09 07:03
from __future__ import unicode_literals

import acutserver.core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acutserver', '0014_user_profile_thumb_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to=acutserver.core.models.user_directory_path)),
                ('body', models.TextField(null=True)),
                ('post_type', models.PositiveIntegerField(default=0)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='acutserver.User')),
            ],
        ),
    ]
