# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acutserver', '0022_auto_20170508_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
