# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acutserver', '0023_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
