"""
Django settings for acut project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import boto
from boto.s3.connection import S3Connection
from acutserver.core.api_keys import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'acutserver',
    'sorl.thumbnail',
    'gcm',
    #'social_django',
    #'rest_framework',
    #'rest_framework_swagger',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'acut.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR,'acut','templates')
          ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'acut.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE':'django.db.backends.mysql',
        'NAME':'Acut_DB',
        'USER':os.environ.get('DB_USER'),
        'PASSWORD':os.environ.get('DB_PW'),
        'HOST':'dataserver.cfquaioenwar.ap-northeast-2.rds.amazonaws.com',
        'PORT':'3306',
    }
    }


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

#AUTHENTICATION_BACKENDS = [
#        'social_core.backends.google.GoogleOAuth2', # Google
#        'social_core.backends.facebook.FacebookOAuth2', # Facebook
#        'django.contrib.auth.backends.ModelBackend', 
#]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/


TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/


STATIC_URL = '/static/'
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATIC_ROOT = os.path.join(PROJECT_DIR,'static')
#STATIC_DIRS = [
#      os.path.join(BASE_DIR, 'static'),
#    ]

#REST_FRAMEWORK = {
#   'DEFAULT_AUTHENTICATION_CLASSES': 
#    ('rest_framework.authentication.TokenAuthentication'),
#    'DEFAULT_PERMISSION_CLASSES': 
#    ('rest_framework.permissions.IsAuthenticated',)
#}




DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

DATA_UPLOAD_MAX_MEMORY_SIZE = None
DATABASE_OPTIONS = {'charset': 'utf8'}
TIME_ZONE = 'Asia/Seoul'

AWS_S3_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
AWS_S3_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
#AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
AWS_STORAGE_BUCKET_NAME = "acut-fullsize-image"
AWS_REGION = 'ap-northeast-2'
AWS_S3_URL_PROTOCOL = 'https'
AWS_QUERYSTRING_QUTH = False
AWS_S3_HOST = 's3.ap-northeast-2.amazonaws.com' 
MEDIA_URL = 'rn:aws:s3:::%s/'%AWS_STORAGE_BUCKET_NAME

EMAIL_HOST = "smtp.sendgrid.net"
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get('SENDGRID_ID')
EMAIL_HOST_PASSWORD = os.environ.get('SENDGRID_PW')
EMAIL_USE_TLS = True

EMAIL_BACKEND = "sgbackend.SendGridBackend"
SENDGRID_API_KEY = os.environ.get('SENDGRID_API_KEY') 

GCM_APIKEY = get_gcm_key()
